version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflows/step1_quantify.wdl
    name: "RNAEditingQuantification"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/step2_aggregate.wdl
    name: "RNAEditingSampleAggregation"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/step3_normalize.wdl
    name: "RNAEditingNormalization"



    
    
